/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtlConsignacion;
import Controlador.CtlCuenta;
import Controlador.CtlUsuario;
import Modelo.ClsConsignacion;
import Modelo.ClsCuenta;
import Modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Lizeth1304
 */
public class IngresoCliente extends javax.swing.JFrame {

    /**
     * Creates new form IngresoCliente
     */
    //Se instancia los controladores para poder hacer uso en toda la clase
    CtlConsignacion controladorConsignacion;
    CtlCuenta controladorCuenta;
    public IngresoCliente() {
        initComponents();
        controladorConsignacion = new CtlConsignacion();
        controladorCuenta = new CtlCuenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnConsignacion = new javax.swing.JButton();
        btnAccederCuenta = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "¿Qué desea hacer?", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        btnConsignacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/699347-icon-74-document-search-48_1.png"))); // NOI18N
        btnConsignacion.setText("Consignar");
        btnConsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsignacionActionPerformed(evt);
            }
        });

        btnAccederCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/Untitled-2-35-32.png"))); // NOI18N
        btnAccederCuenta.setText("Acceder");
        btnAccederCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederCuentaActionPerformed(evt);
            }
        });

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/lock-32_1.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnConsignacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btnAccederCuenta)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsignacion)
                    .addComponent(btnAccederCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnCerrar)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsignacionActionPerformed
        //Para ingresar a la ventana de la acción consignar, primero se pide el número de la cuenta
        //y se va al método buscar para hacer la validación del dato, luego en la condición,
        //se hace la condición para que ingrese a la ventana de consignar y realice la acción
        int cuenta = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de la cuenta que desea consultar: ").trim());
        ClsConsignacion usu = controladorConsignacion.SolicitudBuscar(cuenta);
        if(usu.getPassword()!=null){
               Consigna consigna= new Consigna();
        dispose();
        consigna.setVisible(true);
        }
    }//GEN-LAST:event_btnConsignacionActionPerformed

    private void btnAccederCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederCuentaActionPerformed
        
        //Se pide el número de la cuenta que desea ver la información requerida
        //y se va al método buscar para hacer la validación del dato, luego en la condición,
        //se hace la condición para que ingrese a la ventana de acceder y se muestra la información de la consulta
         int cliente = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de la cuenta que desea consultar: ").trim());
        ClsCuenta usu = controladorCuenta.SolicitudBuscar(cliente);
        if(usu.getPassword()!=null){
               Cuenta placa= new Cuenta(cliente);
        dispose();
        placa.setVisible(true);
        }
        
    }//GEN-LAST:event_btnAccederCuentaActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        //Acción del botón atrás para visualizar de nuevo la ventana login
        Login ven = new Login();
        dispose();
        ven.setVisible(true); 
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccederCuenta;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsignacion;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
